version: '3.7'
services:
  bank:
    container_name: bank
    build:
      context: '.'
      args:
        - APP_ENV=development
        - COMPOSER_NO_INTERACTION=0
    image: bank
    ports:
      - 3006:80
    volumes:
      - ./src:/app
    command: bash -c "composer update --lock --prefer-source && supervisord"
